# FROM node:18

# WORKDIR /app
# COPY spa .

# RUN npm install

# COPY spa .
# ENV PORT=4000
# EXPOSE $PORT

# ENTRYPOINT ["npm", "start"]

# Stage 1: Build the React app
FROM node:18 AS builder
WORKDIR /app
COPY spa/package.json spa/package-lock.json ./
RUN npm install
COPY spa .
RUN npm run build

# Stage 2: Serve the optimized build with NGINX
FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
