name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: List files in the repository
        run: ls -la

      - name: Install Docker Compose
        run : |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Build and Run Docker Compose
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }} #pass secrete to Docker
        run: |
          docker-compose build
          docker-compose run api rake db:setup
          docker-compose run api rake db:migrate
          docker-compose up -d

      # - name: Run Tests
      #   run: docker-compose run api bundle exec rspec
