name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint code with Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUBOCOP_CONFIG_FILE: ../api/.rubocop.yml
          IGNORE_GENERATED_FILES: true
          IGNORE_GITIGNORED_FILES: true
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_TYPESCRIPT: true
          VALIDATE_HTML: true

  build-and-test:
    runs-on: ubuntu-latest
    needs: lint  # This ensures linting runs first
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files in the repository
        run: ls -la

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Build and Run Docker Compose
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}  # Pass secret to Docker
        run: |
          docker-compose build
          docker-compose run api rake db:setup
          docker-compose run api rake db:migrate
          docker-compose up -d

  # Placeholder for future deployment stage
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build-and-test
  #   steps:
  #     - name: Deploy to Production
  #       run: echo "Deployment step goes here"
